# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171119_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
